CREATE TABLE PERSONA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255),
    genero VARCHAR(255),
    edad INT,
    identificacion VARCHAR(255),
    direccion VARCHAR(255),
    telefono VARCHAR(255)

);

CREATE TABLE CLIENTE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    PERSONA_ID INT,
    CONTRASENA VARCHAR(255),
    ESTADO VARCHAR(255),
    CONSTRAINT fk_persona FOREIGN KEY (PERSONA_ID) REFERENCES PERSONA(id)
);

CREATE TABLE CUENTA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO_CUENTA VARCHAR(50) NOT NULL UNIQUE,
    TIPO VARCHAR(50) NOT NULL,
    SALDO_INICIAL DECIMAL(15,2) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    CLIENTE_ID INT,
    CONSTRAINT fk_cliente FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(id)
);

CREATE TABLE MOVIMIENTO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    FECHA TIMESTAMP NOT NULL,
    SALDO_INICIAL DECIMAL(15,2) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    MOVIMIENTO DECIMAL(15,2) NOT NULL,
    SALDO_DISPONIBLE DECIMAL(15,2) NOT NULL,
    CUENTA_ID INT,
    CONSTRAINT fk_cuenta FOREIGN KEY (CUENTA_ID) REFERENCES CUENTA(id)
);